-- Reshape: a build carries TWO aircraft, each with its own quality and its own
-- 5-roll Reset Effect panel, so the three flat columns become one nested blob
-- keyed by aircraft slot ("0" / "1"). The dropped columns never held anything
-- but their defaults — the picker shipped in the same uncommitted cycle and
-- was never used — so there is nothing to migrate across.
-- SQL generated by `prisma migrate diff`; the drop is destructive, which is why
-- `migrate dev` could not write it non-interactively.
ALTER TABLE "builds" DROP COLUMN "aircraft_id",
DROP COLUMN "aircraft_quality",
DROP COLUMN "aircraft_reset_slots",
ADD COLUMN     "aircraft_selections" JSONB NOT NULL DEFAULT '{}';
